language: php
php:
  - '5.6'
env:
  - DB=mysql
install:
  - composer install
script:
  - phpunit --configuration phpunit_mysql.xml --coverage-text
deploy:
  provider: heroku
  app:
      master: taskboard-staging
      production: taskboard-production