# -*- mode: ruby -*-
# vi: set ft=ruby :
begin
  load './vagrant-provisioning.rb'
rescue LoadError => error
  puts error.message
end
Vagrant.configure(2) do |config|
  config.vm.box = "digital_ocean"
  config.vm.hostname = 'taskboards.top'
  config.vm.synced_folder "../src/", "/var/www/taskboard/src", create: true, group: "www-data", owner: "www-data"
  config.vm.synced_folder "../public/", "/var/www/taskboard/public", create: true, group: "www-data", owner: "www-data"
  config.vm.synced_folder "../config/", "/home/vagrant/config", create: true, type: "rsync"
  config.vm.provider :digital_ocean do |provider,override|
    override.ssh.private_key_path = '~/.ssh/do_rsa'
    override.vm.box = 'digital_ocean'
    override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
    provider.token = ENV['DIGITALOCEAN_TOKEN']
    provider.image = 'ubuntu-14-04-x64'
    provider.region = 'fra1'
    provider.size = '1024mb'
  end
  config.vm.provision "write-host", type: "shell" do |s|
    s.inline = "service nginx stop && sed -i 's/server_name\ taskboard\.dev/server_name\ taskboards\.top/g' /etc/nginx/sites-enabled/taskboards.top && service nginx start"
  end
  config.vm.provision "write-mail-host", type: "shell" do |s|
    s.inline = "service postfix stop && sed -i 's/taskboard\.dev/taskboards\.top/g' /etc/postfix/main.cf && service postfix start"
  end
end
